CoffeeShop.destrol_all

CoffeeShop.create(name: "Balancero", location: "Astoria")
CoffeeShop.create(name: "Blue Stone", location: "Financial Distict")
CoffeeShop.create(name: "Toby's Estate", location: "Williamsburg")
CoffeeShop.create(name: "Ceremonia", location: "Williamsburg")
CoffeeShop.create(name: "Birch", location: "Murray Hill")
CoffeeShop.create(name: "Sant Ambroeus", location: "Soho")
CoffeeShop.create(name: "La Colombe", location: "Financial Distict")
CoffeeShop.create(name: "Cha Cha Matcha", location: "Soho")
CoffeeShop.create(name: "Ground Support Cafe", location: "Soho")
CoffeeShop.create(name: "Blue Bottle", location: "Meat Packing District")
CoffeeShop.create(name: "Oslo Coffee Roaster", location: "Williamsburg")
CoffeeShop.create(name: "Burley Coffee", location: "Williamsburg")
CoffeeShop.create(name: "Maman", location: "Meat Packing District")
CoffeeShop.create(name: "Joe Coffee Company", location: "Soho")
CoffeeShop.create(name: "Coffee Project", location: "Lower East Side")
CoffeeShop.create(name: "Stumptown Coffee Roasters", location: "Soho")
CoffeeShop.create(name: "Sey Coffee", location: "East Williamsburg")
CoffeeShop.create(name: "Ninth Street Espresso", location: "East Village")
CoffeeShop.create(name: "The Elk", location: "West Village")
CoffeeShop.create(name: "Devoción", location: "Williamsburg")
CoffeeShop.create(name: "Bar Beau", location: "Williamsburg")
CoffeeShop.create(name: "Sawada Coffee", location: "China Town")
CoffeeShop.create(name: "Astoria Coffee", location: "Astoria")
CoffeeShop.create(name: "Black Press Coffee", location: "Upper West Side")
CoffeeShop.create(name: "Lazy Suzy", location: "Bushwick")
CoffeeShop.create(name: "Culture Espresso", location: "Midtown East")
CoffeeShop.create(name: "Parva Bakeshop", location: "Jackson Heights")
CoffeeShop.create(name: "Maman", location: "Tribeca")
CoffeeShop.create(name: "Rex", location: "Hell's Kitchen")
CoffeeShop.create(name: "Southside Coffee", location: "South Park Slope")